config/routes.rb
  Rails.application.routes.draw do
  get 'store/index'
  get 'order_products/create'

  get 'order_products/update'

  get 'order_products/destroy'
  get 'orders/new'

  get 'carts/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   mount Ckeditor::Engine => '/ckeditor'
  root 'homes#index'
  get '/home', to: 'homes#index'
  get '/payment', to: 'products#payment'
  get '/products', to: 'products#index'
  get '/designs', to: 'designs#index'
  get '/bedroom_boy', to: 'designs#bedroom_boy'
  get '/bedroom_girl', to: 'designs#bedroom_girl'
  get '/kitchen', to: 'designs#kitchen'
  get '/living_room', to: 'designs#living_room'
  get '/apartment', to: 'designs#apartment'
  get '/villa', to: 'designs#villa'
  get '/abouts', to: 'abouts#index'
  get '/helps' , to: 'helps#index'
  get '/contacts' , to: 'contacts#contact'

  resource :cart, only: [:show]
  resources :order_products, only: [:show, :create, :update, :destroy]

  resources :orders
  resources :contacts
 resources :products, only: [:index, :show]

  devise_for :users, controllers: { registration: "registration" }

end

app/models/product.rb
class Product < ActiveRecord::Base

	 has_attached_file :image, styles: { large: "600x600>", medium: "250x250>", thumb: "100x100>" }
   # ,
       #  :storage => :google_drive,
       # :google_drive_credentials => "#{Rails.root}/config/google_drive.yml",
       # :google_drive_options => {
       #     public_folder_id: '0B6QUwbBS7M0Ta2pudWMzeFZoRUk',
       #       :path => proc { |style| "#{style}_#{id}_#{image.original_filename}" }
       # }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    belongs_to :brand
    
    enum status: [:active, :archived]
    has_many :order_products

    default_scope { where(active: true) }
    def self.search(search)
         # Title is for the above case, the OP incorrectly had 'name'
         where("name LIKE ?", "%#{search}%")
    end

end

app/controllers/categories/products_controllers.rb
# class Categories::ProductsController < ApplicationController
# 	def index
# 		@products = Product.where(category_id: params[:categoty_id])
# 		@products = @products.limit(9)
# 	end

#   	def product
#     @products = Product.all
#   	end

#   	def show
#   		@products = Product.friendly.where(params[:name])
# 	end
# end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 before_action :load_product, only: :show
  before_action :load_all
  before_action :load_brand_and_style_and_collection
  def index
    @params = params.reject { |k| ["action","controller"].include?(k.to_s) }
    brand_id = params[:brand_id]
    style_id = params[:style_id]
    collection_id = params[:collection_id]
    @order_product = current_order.order_products.new
    if params[:search].present?
      @products = Product.search(params[:search])
    else
      @products = Product.all
    end
   @products = @products.where(brand_id: brand_id) if brand_id.present?
   @products = @products.where(style_id: style_id) if style_id.present?
   @products = @products.where(collection_id: collection_id) if collection_id.present?
   @products = @products.order("created_at DESC").page(params[:page]).per(9)
   @products = @products.order("created_at DESC").page(params[:page]).per(9)
   @products = @products.order("created_at DESC").page(params[:page]).per(9)
  end
  
  def show
  end
  
  def load_product
    @product = Product.find_by(id: params[:id]) 
    @pre_product = Product.find_by(id: params[:pre_product_id])
    # Create cart for user
    @order_product = current_order.order_products.new
    # count weight for product
    if @pre_product != @product
      @pre_product.goto ||= {}
      @hash = @pre_product.goto
      if @pre_product.goto[params[:id]].nil?
        @pre_product.goto[params[:id]] = 1
        else @hash.keys.each do |k|
            if k.to_i == @product.id
              @last_weight = @hash[k].to_i
              @hash[k] = @hash[k].to_i + 1
            end
        end
      end
      @pre_product.save
    end
    if @product.goto.nil?
      @hot_products = []
      @allIdProduct = Product.all.ids
      @newIds = @allIdProduct - [@product.id]
      if @newIds.length > 4 
        @randomIds = @newIds.sample(5)
      else 
        @randomIds = @newIds.sample(@newIds.length)
      end
    @randomIds.each do |id|
      @hot_products << Product.find(id)
    end
   else
      @weight_products = @product.goto.length
      @random_variable = 2  
      @hot_products = Product.where(id: @product.goto.keys) 
        if (@weight_products > 2)
          @new_product = @product.goto.sort_by {|key, value| value}.reverse
          @new_product = @new_product[0..2]
        else 
          @random_variable = 5 - @weight_products
          @new_product = @product.goto.sort_by {|key, value| value}.reverse
        end
      @ids = @new_product.collect {|key, value| key.to_i}
      @products = []
      @ids.each do |id| 
         @products << Product.find(id)
      end
      @allIdProduct = Product.all.ids
      if @allIdProduct.length < @random_variable + @ids.length 
        @random_variable = @allIdProduct.length - @ids.length
      end
      @newIds = @allIdProduct - @ids - [@product.id]
      @randomIds = @newIds.sample(@random_variable)
      @randomIds.each do |id|
        @products << Product.find(id)
      end
      @hot_products = @products
    end
  end
  private
    def load_product_by_brand
      @brand = Brand.find_by id: params[:brand_id]
      if @brand
        @products = @brand.products.page(params[:page]).per(9)

      end
    end

    def load_product_by_style
      @style = Style.find_by id: params[:style_id]
      if @style
        @products = @style.products.page(params[:page]).per(9)
      end
    end

    def load_product_by_collection
      @collection = Collection.find_by id: params[:collection_id]
      if @collection
        @products = @collection.products.page(params[:page]).per(9)
      end
    end

    def load_all
      if @brand.nil? && @style.nil? && @collection.nil?
        @products = Product.page(params[:page]).per 12
      end
    end

    def load_brand_and_style_and_collection
      @style = Style.all
      @brand = Brand.all
      @collection = Collection.all
    end

    def products_params
      params.require(:products).permit(:name, :description, :price, :status, :image)
    end
end

app/views/products/_product_details.html.erb
<%= form_for order_product, remote: true do |f| %>
<div class="col-md-4">  
   <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
   <%= f.hidden_field :product_id, value: product.id %>
</div>
<div class="col-md-4">
   <div class="input-group-btn" style="width: 10px;">
      <div class="input-group-btn" style="width: 10px; float: ">
         <%= f.submit "Add to Cart", class: "btn btn-primary"%>
         
      </div>
   </div>
</div>
<% end %> 

app/views/products/_product_row.html.erb
<div class="col-md-4">
   <div class="product">
      <div class="img">
          <%= link_to (image_tag product.image.url(:medium)), product_path(product, pre_product_id: product.id) %>
      </div>
      <div class="information">
         <a class="header">
         <%= link_to product.name, product_path(product, pre_product_id: product.id) %></a>
         <br>
         <%= number_to_currency product.price %> 
         <br>
         <%= product.status%>
         <%= form_for order_product, remote: true do |f| %>
         <!-- <div class="input-group-btn" style="width: 10px; float: ">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary" %>
            </div> -->
         <% end %>
      </div>
   </div>
</div>

app/views/products/index.html.erb
<div class="navigation">
   <nav class="navba navbar-default">
      <div class="navbar-header">
         <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         </button>            
      </div>
      <div class="collapse navbar-collapse js-navbar-collapse">
         <div class="col-md-1"></div>
         <div class="col-md-5">
            <ul class="nav navbar-nav"  style="margin-top: 10px">
               <li><%= link_to "HOME", home_path() %></li>
               <li class="dropdown mega-dropdown">
                  <%= link_to "PRODUCT", products_path() , class: "active"%>
                  <ul class="dropdown-menu mega-dropdown-menu">
                     <li class="col-sm-4">
                        <ul>
                           <li class="title-product">BRAND
                              <% @brand.each do |brand| %>
                           <li class="content-header"><%= link_to brand.name, products_path(brand_id: brand.id) %>
                           </li>
                           <% end %>
                           </li>
                        </ul>
                     </li>
                     <li class="col-sm-4">
                        <ul>
                           <li class="title-product">STYLE
                              <% @style.each do |style| %>
                           <li class="content-header"><%= link_to style.name, products_path(style_id: style.id) %></li>
                           <% end %>
                           </li> 
                        </ul>
                     </li>
                     <li class="col-sm-4">
                        <ul>
                           <li class="title-product">COLLECTION
                              <% @collection.each do |collection| %>
                           <li class="content-header"><%= link_to collection.name, products_path(collection_id: collection.id) %></li>
                           <% end %>
                           </li>                       
                        </ul>
                     </li>
                  </ul>
               </li>
               <li> <%= link_to "DESIGN", designs_path() %> </li>
               <li><%= link_to "ABOUT", abouts_path() %></li>
               <li><a href="/contacts">CONTACT</a></li>
            </ul>
         </div>
         <div class="col-md-6" style="padding-right: 75px;">
            <ul class="nav navbar-nav navbar-right">
               <li><a href="/cart">
                  <i class="fa fa-shopping-cart fa-lg " ></i>
                  </a>
               </li>
               <li>
                  <a class="account" href="<%= new_user_session_path %>"><i class="fa fa-user fa-lg"></i></a>
               </li>
               <li>
                  <a href="javascript:void(0);" style="margin-top: 5px;">
                     <div class="search_form" >
                        <%= form_tag(products_path, :method => "get", id: "search-form") do %>
                        <%= text_field_tag :search, params[:search], placeholder: "Search products" %>
                        <% end %>
                     </div>
                  </a>
               </li>
            </ul>
         </div>
      </div>
   </nav>
</div>
<div class ="main">
   <div class="body container-fluid">
      <div class="col-md-3">
         <h3 class="title"><%= link_to "PRODUCT", products_path %></h3>
         <div class="sidebartotal">
            <div class="sidebar">
               <ul class="">
                  <li class="filter-products">FILTER PRODUCTS</li>
                  <li>BRAND</li>
                     <% @brand.each do |brand| %>
                  <li class="content-id"><%= link_to brand.name, products_path(brand_id: brand.id) %>
                  </li>
                  <% end %>
                  <li>STYLE </li> 
                     <% @style.each do |style| %>
                  <li class="content-id"><%= link_to style.name, products_path(style_id: style.id) %></li>
                  <% end %>
               </ul>
            </div>
            <div class="sidebar-collection">
               <ul>
                  <li>COLLECTION </li>
                     <% @collection.each do |collection| %>
                  <li class="content-id"><%= link_to collection.name, products_path(collection_id: collection.id) %></li>
                  <% end %>
               </ul>
            </div>
         </div>
      </div>
      <div class="col-md-9 content">
         <% @products.each do |product| %>
         <%= render "product_row", product: product, order_product: @order_product %>
         <% end %>
      </div>
      <div class="next-page">
         <%= paginate @products, theme: 'twitter-bootstrap-3' %>
      </div>
   </div>
</div>

app/views/products/show.html.erb
<%= javascript_include_tag "special/details-product"%>
<div class="navigation">
   <nav class="navba navbar-default">
      <div class="navbar-header">
         <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
         <span class="sr-only">Toggle navigation</span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         </button>            
      </div>
      <div class="collapse navbar-collapse js-navbar-collapse">
         <div class="col-md-1"></div>
         <div class="col-md-5">
            <ul class="nav navbar-nav"  style="margin-top: 10px">
               <li><%= link_to "HOME", home_path() %></li>
               <li class="dropdown mega-dropdown">
                  <%= link_to "PRODUCT", products_path() %>
                  <ul class="dropdown-menu mega-dropdown-menu">
                     <li class="col-sm-4">
                        <ul>
                           <li class="title-product">BRAND
                              <% @brand.each do |brand| %>
                           <li class="content-header"><%= link_to brand.name, products_path(brand_id: brand.id) %>
                           </li>
                           <% end %>
                           </li>
                        </ul>
                     </li>
                     <li class="col-sm-4">
                        <ul>
                           <li class="title-product">STYLE
                              <% @style.each do |style| %>
                           <li class="content-header"><%= link_to style.name, products_path(style_id: style.id) %></li>
                           <% end %>
                           </li> 
                        </ul>
                     </li>
                     <li class="col-sm-4">
                        <ul>
                           <li class="title-product">COLLECTION
                              <% @collection.each do |collection| %>
                           <li class="content-header"><%= link_to collection.name, products_path(collection_id: collection.id) %></li>
                           <% end %>
                           </li>                       
                        </ul>
                     </li>
                  </ul>
               </li>
               <li> <%= link_to "DESIGN", designs_path() %> </li>
               <li><%= link_to "ABOUT", abouts_path() %></li>
               <li><a href="/contacts">CONTACT</a></li>
            </ul>
         </div>
         <div class="col-md-6" style="padding-right: 75px;">
            <ul class="nav navbar-nav navbar-right">
               <li><a href="/cart">
                  <i class="fa fa-shopping-cart fa-lg " ></i>
                  </a>
               </li>
               <li>
                  <a class="account" href="<%= new_user_session_path %>"><i class="fa fa-user fa-lg"></i></a>
               </li>
               <li>
                  <a href="javascript:void(0);" style="margin-top: 5px;">
                     <div class="search_form" >
                        <%= form_tag(products_path, :method => "get", id: "search-form") do %>
                        <%= text_field_tag :search, params[:search], placeholder: "Search products" %>
                        <% end %>
                     </div>
                  </a>
               </li>
            </ul>
         </div>
      </div>
   </nav>
</div>
<div class="content-details">
<div class="container">
   <div class="col-md-6">
      <p>
      <h3 class="name-details"><%= @product.name %></h3>
      </p>
      <div class="image">
         <%= image_tag @product.image.url(:large) %>
      </div>
   </div>
   <div class="col-md-6">
      <div class="product">
         <h2 class="name-product-details"> PRODUCT DESCRIPTION </h2>
         <hr>
         <div class="containaer">
            <div class="col-md-4">
               <p>
                  $<%= @product.price %>
               </p>
            </div>
            <div class="col-md-8">
               <% product = @products.find_by(id: params[:id]) %>
               <%= render "product_details", product: product, order_product: @order_product %>
            </div>
            </br>
            </br>
            </br>
            </br>
            <div class ="page">
               <p>
                  <%= @product.description %>
               </p>
            </div>
         </div>
      </div>
   </div>
   <div class ="name">
      <h1>Related Product</h1>
   </div>
   <div class="row">
      <div class="container">
         <div class="col-md-12">
            <div class="carousel slide" id="myCarousel">
               <div class="carousel-inner">
                  <div class="item active">
                     <% @hot_products.each do |hot_product| %>
                     <div class="col-lg-2 col-xs-2 col-md-2 col-sm-2" style="width: 20%">
                        <div class="img-product">
                           <%= link_to (image_tag hot_product.image.url(:medium)),
                              product_path(hot_product,pre_product_id: product.id) %>
                        </div>
                        <a href=""><%= hot_product.name %> </a>
                        <br>
                        <b>
                           <p><%= hot_product.price %></p>
                        </b>
                     </div>
                     <% end %>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>