config/routes.rb
  Rails.application.routes.draw do
  get 'store/index'
  get 'order_products/create'

  get 'order_products/update'

  get 'order_products/destroy'
  get 'orders/new'

  get 'carts/show'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   mount Ckeditor::Engine => '/ckeditor'
  root 'homes#index'
  get '/home', to: 'homes#index'
  get '/payment', to: 'products#payment'
  get '/products', to: 'products#index'
  get '/designs', to: 'designs#index'
  get '/bedroom_boy', to: 'designs#bedroom_boy'
  get '/bedroom_girl', to: 'designs#bedroom_girl'
  get '/kitchen', to: 'designs#kitchen'
  get '/living_room', to: 'designs#living_room'
  get '/apartment', to: 'designs#apartment'
  get '/villa', to: 'designs#villa'
  get '/abouts', to: 'abouts#index'
  get '/helps' , to: 'helps#index'
  get '/contacts' , to: 'contacts#contact'

  resource :cart, only: [:show]
  resources :order_products, only: [:show, :create, :update, :destroy]

  resources :orders
  resources :contacts
 resources :products, only: [:index, :show]

  devise_for :users, controllers: { registration: "registration" }

end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :products
end

app/models/collection.rb
class Collection < ActiveRecord::Base
	has_many :products
end

app/models/contact.rb
class Contact < ActiveRecord::Base
	
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :order_status
  has_many :order_products
  before_create :set_order_status
  before_save :update_subtotal
    
  enum pay_type: [:Direct, :Online]

  def subtotal
    order_products.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end

  private

    def set_order_status
      self.order_status_id = 1
    end

    def update_subtotal
      self[:subtotal] = subtotal
    end
end

app/models/order_product.rb
class OrderProduct < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
  belongs_to :cart

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ActiveRecord::Base
  has_many :orders
end

app/models/product.rb
class Product < ActiveRecord::Base

	 has_attached_file :image, styles: { large: "600x600>", medium: "250x250>", thumb: "100x100>" }
   # ,
       #  :storage => :google_drive,
       # :google_drive_credentials => "#{Rails.root}/config/google_drive.yml",
       # :google_drive_options => {
       #     public_folder_id: '0B6QUwbBS7M0Ta2pudWMzeFZoRUk',
       #       :path => proc { |style| "#{style}_#{id}_#{image.original_filename}" }
       # }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

    belongs_to :brand
    
    enum status: [:active, :archived]
    has_many :order_products

    default_scope { where(active: true) }
    def self.search(search)
         # Title is for the above case, the OP incorrectly had 'name'
         where("name LIKE ?", "%#{search}%")
    end

end

app/models/style.rb
class Style < ActiveRecord::Base
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role
  ATTRIBUTES_PARAMS = [:email, :password, :username ]
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_products = current_order.order_products
  end

  def create
  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
	def index

	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  	
  	if user_signed_in?
  		
  	else
  		redirect_to new_user_session_path

  	end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	before_action :load_product 
	def index
		@products = Product.all
		@products = Product.limit(6)
		@collection = Collection.limit(3)
	end

	def show
		@products = Product.find(params[:id])
		@collection = Collection.find(params[:id])
		respond_to do |format|
			format.html { render :text => @products.index }
		end
	end

private
	def load_product
		@products = Product.find_by id: params[:product_id]
	end

	# def load_collection
	# 	@collection = Collection.find_by id: params[:collection_id]
	# end

	def homes_params
		params.require(:products).permit( :image)
	end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	@products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def get_random_products(max_value = 10)
	# Product.where(id: Product.pluck(:id).sample(10))
	Product.limit(5).order("RANDOM()")
	
	# Product.first(:offset => rand(Product.count)
# products = Product.scoped.select(:id);nil
# Product.find( products.first( Random.rand( products.length )).last )
	end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/funiture_helper.rb
module FunitureHelper
end

app/helpers/funitures_helper.rb
module FunituresHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order.order_products.size} products in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>

app/views/layouts/_footer.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<footer>
   <div class="container">
      <div class="row">
         <div class="col-md-3">
            <ul>
               <li>
                  <h4><b>Main Menu</b></h4>
               </li>
               <a href="/home">
                  <li>Home</li>
               </a>
               <a href="/products">
                  <li>Product </li>
               </a>
               <a href="/designs">
                  <li>Design</li>
               </a>
               <a href="/abouts">
                  <li>About</li>
               </a>
               <a href="/contacts">
                  <li>Contact</li>
               </a>
            </ul>
         </div>
         <div class="col-md-3">
            <ul>
               <li>
                  <h4><b>Made in America</b></h4>
               </li>
               <li>All of our products are proudly made right here in America</li>
            </ul>
         </div>
         <div class="col-md-3">
            <ul>
               <li>
                  <h4><b>Here to Help</b></h4>
               </li>
               <li>If you need help setting up your new furniture. we are glad to lend a hand</li>
            </ul>
         </div>
         <div class="col-md-3">
            <ul>
               <li>
                  <h4><b>Keep in Touch</b></h4>
               </li>
               <li>Sign up for our newsletter and be the first to knoww about coupons and special promotions</li>
            </ul>
            <div class="link_to">
               <a href="http://facebook.com/quancoi1995"><span class="fa fa-facebook" style="color: blue;"></span>
               </a>
               <a href="http://mail.google.com"><span class="fa fa-google-plus" style="color: red;"></span>
               </a>
               <a href="http://www.youtube.com/channel/UCOR5-w-RXIioLGqj3x2-sCQ"><span class="fa fa-youtube" style="color: red;"></span>
               </a>
            </div>
         </div>
      </div>
   </div>
</footer>

app/views/layouts/_header.html.erb
<div class="header_top">
   <div class="container">
      <div class="col-md-12" >
         <div class="logo">
            <a href="/home"><img src="<%= asset_path('logo_550x.png') %>"></a>
         </div>
         <div class="hed_right">
            <ul>
               <li><a href="/helps"  style="color: #8a756b;">Help</a>
               </li>
               <li><a href="/contacts" style="color: #8a756b;">Contact</a>
               </li>
               <li><a href="/account" style="color: #8a756b;">
                  <% if current_user %>
                  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
                  <% else %>
                  <%= link_to "My Account", new_user_session_path %>
                  <% end %></a>
               </li>
            </ul>
            <div class="header-contact">
               <ul>
                  <li>
                     <span class="fa fa-phone" style="color: #abbda5">  </span> 0111.222.333
                  </li>
                  <li>
                     <span class="fa fa-envelope"  style="color: #abbda5"></span> email@example.com
                  </li>
               </ul>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FunituresApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	
<%= yield %>
<%= render 'layouts/footer' %>

</body>
</html>